name: Frontend Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ 14 ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
  
      - name: Install npm packages
        run: npm ci --omit=optional
        working-directory: frontend
  
      - name: Run tests
        run: npm run test:unit
        working-directory: frontend
