name: Frontend Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2

    - name: Install npm packages
      run: npm ci --omit=optional
      working-directory: frontend

    - name: Run tests
      run: npm run test:unit
      working-directory: frontend
